SELECT YRWK,
       BasePartNum,
       StartTime,
       AsmPlanGroup,
       AsmMachType,
       AsmPlatform,
       AsmLineAssigned,
       ATBuilt,
       WorkOrdNum,
       ChangeOverMin,
       Thoeretical,
       TotalTimeSec,
       Eff,
       DownTime,
       LossQtyDuetoDT,
       [DT%],
       Eff + [DT%] AS Prodictivity,
       'SHIFT 1' AS Shift
FROM ProcessDetails.dbo.RPT_WO_Eff_Downtime