SELECT EMP_EmpID,
       EMP_LongName,
       EMP_StartDate,
       EMP_FunctionArea,
       EMP_JobTitle,
       EMP_ShiftDesc,
       EMP_Agency,
       EMP_Dept,
       EMP_Role,
       SupRole,
       SupName,
       EMP_TempStatus,
       EMP_EmpStatusDesc,
       OccurrenceHandlingPoints,
       HoursWorked,
       OccurrencePoints,
       StatusUpdated,
       DATE
FROM [Timeclock].[dbo].OccurrencePts_GraduationHrs