SELECT *,CASE 
WHEN Platform LIKE 'ARCADIA%' THEN 'ARCADIA'
WHEN Platform LIKE 'INDUS-C%' THEN 'INDUS-C'
WHEN Platform LIKE 'RACKBACK%' THEN 'RACKBACK'
WHEN Platform LIKE 'FLATBACK%' THEN 'FLATBACK'
WHEN Platform LIKE 'BIJLEE%' THEN 'BIJLEE'
WHEN Platform LIKE 'MACTRUCK%' THEN 'MACTRUCK'
WHEN Platform LIKE 'ICEBLINK%' THEN 'ICEBLINK'
WHEN Platform LIKE 'ABERDEEN%' THEN 'ABERDEEN'
WHEN Platform LIKE 'INTERLAKEN%' THEN 'INTERLAKEN'
WHEN Platform LIKE 'DRAGONFISH%' THEN 'DRAGONFISH'
WHEN Platform LIKE 'INDUS-S%'THEN 'INDUS-S'
WHEN Platform LIKE 'JELLYDONUT%' THEN 'JELLYDONUT'
WHEN Platform LIKE 'JELLYFISH%' THEN 'JELLYFISH'
WHEN platform LIKE 'IXION%' THEN 'IXION'
WHEN platform LIKE '%JUICE-BOX%' THEN 'JUICE-BOX'
ELSE Platform
END as PlatformUpdated
,CASE
WHEN DefectPartLoc LIKE '%BIOS%' THEN 'BIOS'
WHEN DefectPartLoc LIKE '%BMC%' THEN 'BMC'
WHEN DefectPartLoc LIKE '%CPU%' THEN 'CPU'
WHEN DefectPartLoc LIKE '%DIMM%' THEN 'DIMM'
WHEN DefectPartLoc LIKE '%FAN%' THEN 'FAN'
WHEN DefectPartLoc LIKE '%HEATSINK%' THEN 'HEATSINK'
WHEN DefectPartLoc LIKE '%I2COOL%' THEN 'I2COOL'
WHEN DefectPartLoc LIKE '%NCSI%' THEN 'NCSI'
WHEN DefectPartLoc LIKE '%PE%' THEN 'PE'
WHEN DefectPartLoc LIKE '%CSSD%' THEN 'CSSD'
WHEN DefectPartLoc LIKE '%TANG%' THEN 'TANG'
WHEN DefectPartLoc LIKE '%KA%' THEN 'KA'
WHEN DefectPartLoc LIKE '%HDD%' THEN 'HDD'
WHEN DefectPartLoc LIKE '%SATA%' THEN 'SATA'
WHEN DefectPartLoc LIKE '%PWR%' THEN 'PWR'
WHEN DefectPartLoc LIKE '%MOBO%' THEN 'MOBO'
WHEN DefectPartLoc LIKE '%PCBA%' THEN 'PCBA'
WHEN DefectPartLoc LIKE '%PSU%' THEN 'PSU'
WHEN DefectPartLoc LIKE '%THERMAL%' THEN 'THERMAL'
WHEN DefectPartLoc LIKE '%RISER%' THEN 'RISER'
WHEN DefectPartLoc LIKE '%LUFTIG%' THEN 'LUFTIG'
WHEN DefectPartLoc LIKE '%KOOL_AID%' THEN 'KOOLAID'
WHEN DefectPartLoc LIKE '%MAIN_BOARD%' THEN 'MAIN BOARD'
WHEN DefectPartLoc LIKE '%PCIE%' THEN 'PCIE'
WHEN DefectPartLoc LIKE '%STELE_CABLE%' THEN 'STELE_CABLE'
WHEN DefectPartLoc LIKE '%SSD%' THEN 'SSD'
WHEN DefectPartLoc LIKE '%QSFP%' THEN 'QSFP'
WHEN DefectPartLoc LIKE '%CAT5%' THEN 'CAT5'
WHEN DefectPartLoc LIKE '%LOOPBACK%' THEN 'LOOPBACK'
WHEN DefectPartLoc LIKE '%CDFP%' THEN 'CDFP'
ELSE DefectPartLoc
END AS PartLoc,
    CONVERT(VARCHAR, YEAR(DATEADD(WK, DATEDIFF(DAY, 0, Date) / 7, 3))) 
    + 'W' + REPLICATE('0', 2 - LEN(DATEPART(ISO_WEEK, Date)))
    + CONVERT(VARCHAR, DATEPART(ISO_WEEK, Date)) 
    + 'D' + REPLICATE('0', 2 - LEN(CASE WHEN DATEPART(WEEKDAY, Date) = 1 THEN 7 ELSE DATEPART(WEEKDAY, Date) - 1 END))
    + CONVERT(VARCHAR, CASE WHEN DATEPART(WEEKDAY, Date) = 1 THEN 7 ELSE DATEPART(WEEKDAY, Date) - 1 END) AS PQAYRWKDY,
    --DATENAME(WEEKDAY, Date) AS Days,
    DATEPART(WEEKDAY, Date) - 1 AS Day,
    CONCAT( DATEPART(WEEKDAY, Date) - 1, '.',DATENAME(WEEKDAY, Date)) AS Days,
    ROW_NUMBER() OVER (PARTITION BY AssetTagNum, TestStep ORDER BY Date DESC) AS TestCount
FROM ShopFloorN.[dbo].[RPT_PQAData]
where Plant='FB'
--Date > GETDATE() - 30
ORDER BY Date, AssetTagNum, YRWK, PlanGroup
